### ISSUE TITLE
Folder Deletion Bug

### ISSUE THREAD

**Issue by couchfault** [frozenjava/Cabinet#2]
The `deleteFile()` function logic is flawed:

```
if (file_exists($f)) {
    if (!is_dir($f)) {
        unlink($f);
    } else {
        foreach (preg_grep('/^([^.])/', scandir($f)) as $file) {
        unlink($f . '/' . $file);
    }
    rmdir($f);
}
```

If `$f` is a directory containing at least one non-empty subdirectory then the function will fail. The issue is that it treats all of the contents  of `$f` as flat files. To change this either write it as a recursive function or simply `exec("rm -rf " . escapeshellarg($f))`.

**Comment by frozenjava** [comment]
Fixed
